name = "portfolio"

page = "https://shelled-acorn-8ff.notion.site/Chih-Hua-Chang-s-Portfolio-2468fec935b64ba2a50cd2829f2021df"

theme = "light"

[site]
  [[site.meta]]
  name = "title"
  content = "Chih-Hua Chang's Portfolio"
  [[site.meta]]
  name = "description"
  content = "Hi! Welcome to my portfolio."

  [site.fonts]
  site = 'Nunito'
  navbar = ''
  title = 'Montserrat'
  h1 = 'Montserrat'
  h2 = 'Montserrat'
  h3 = 'Montserrat'
  body = ''
  code = ''
