name = "portfolio"

page = "https://shelled-acorn-8ff.notion.site/Chih-Hua-Chang-s-Portfolio-4a1b4598147e4c11bef2a8fb82c51528"

theme = "light"

[site]
  [[site.meta]]
  name = "title"
  content = "Chih-Hua Chang's Portfolio"
  [[site.meta]]
  name = "description"
  content = "Hi! Welcome to my portfolio."

  [site.fonts]
  site = 'Nunito'
  navbar = ''
  title = 'Montserrat'
  h1 = 'Montserrat'
  h2 = 'Montserrat'
  h3 = 'Montserrat'
  body = ''
  code = ''
